Apex-NoRecoil | Python Build
mgsweet/Apex-NoRecoil-2021 pull request #10
Opened 2021-08-17 12:12 UTC by krampus-nuggets

Hi there, I have rewritten your original AHK script in Python. Python version is meant to be used as a CLI with the following being implemented:

* Toggle for enabling/disabling the recoil-control functionality.
* OCR recognition of which weapon is in slots 1 and 2.
* Key bindings are set to the keyboard characters 1 and 2 for updating and applying the recoil patterns based on which weapons are in which weapon slots.
* I've personally tested and confirmed stability and performant usage. Any additional optimization feedback is welcomed.

2021-08-17 13:35 UTC, mgsweet requested changes
1. rename python/ReadMe.md to python/README.md
2. could you help me create a contributor section in the main README.md with your name there.
3. also it would be great if you can add a section in the main README.md to tell those who are not familiar with AHK to take a look at the python version.

2021-08-17 13:35 UTC, mgsweet commented on python/main.py
> +banners = {
coool

2021-08-17 18:45 UTC, krampus-nuggets commented
Updates have been applied:

* File has been renamed to README in python dir
* Main repo README content has been updated and Contributor table has been added as well

On a side note, when you get a moment you could implement this tool to automatically generate a contributors table in the main README file - https://allcontributors.org/#

@mgsweet

2021-08-18 09:50 UTC, mgsweet approved these changes
Respect!

2021-08-18 09:55 UTC, mgsweet commented
merge it yourself when u think it is ready.

2021-08-18 10:06 UTC, mgsweet commented
> https://allcontributors.org/#

OT every day. Will take a look this night

2021-08-18 12:17 UTC, krampus-nuggets commented
@mgsweet - I don't have write access, so I can't merge the pull request.

2021-08-18 13:36 UTC, mgsweet commented
@krampus-nuggets I think I have invited you. anyway, i would do this

2021-08-18 13:37 UTC, merged

2021-08-18 15:34 UTC, mgsweet commented
@all-contributors please add @krampus-nuggets  for code

2021-08-19 17:20 UTC, mgsweet commented
@krampus-nuggets Take a look at the latest README. Send me a pull request if you have anything else to add.