python-build: ux updates + bug fixes + recoil-pattern tool
mgsweet/Apex-NoRecoil-2021 pull request #19
Opened 2021-08-19 21:07 UTC by krampus-nuggets

Hey, the following updates can be found in this pull request:

* Pattern-Tracker tool for generating recoil-patterns.
* Moving banners to external module.
* Update python and main README files.
* Tool state updates output to one-line source.

2021-08-20 05:41 UTC, mgsweet requested changes
check README review

2021-08-20 05:41 UTC, mgsweet commented on README.md
> +## Update
what is this for?

2021-08-20 05:41 UTC, mgsweet commented on README.md
> +=======
also this one

2021-08-20 15:23 UTC, krampus-nuggets reviewed
I've removed the unneeded heading. Not sure what happened, I blame morning brain.

2021-08-21 03:23 UTC, krampus-nuggets commented
The following additional updates have been pushed as well:

* External config for easier handling of anti-recoil sensitivity and setting the position/dimensions of OCR scan block.
* Minor internal changes
* README info and progress updates

cc @mgsweet

2021-08-21 15:26 UTC, mgsweet approved these changes

2021-08-21 15:26 UTC, merged